apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tg-spam.fullname" . }}-tg-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tg-spam.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tgspam.storage | default "1Gi" }}


